export { userRouter } from "./userRoutes";
export { documentRouter } from "./documentRoutes";
export { familyTreeMemberRouter } from "./familyTreeMemberRoutes";
export { likeRouter } from "./likeRoutes";
export { mediaRouter } from "./mediaRoutes";
export { storyRouter } from "./storyRoutes";
export { commentRouter } from "./commentRoutes";
export { fileRouter } from "./fileRoutes";
export { relationsRouter } from "./relationsRoutes";
